server:
  server_host: 127.0.0.1
  server_port: 8080
  server_authorization_key: aboba
postgres:
  postgres_host: localhost
  postgres_port: 5432
  postgres_user: root
  postgres_password: f7kmXohh
  postgres_database_name: face_scanner
  postgres_ssl_mode: disable
face_scan_api:
  url: https://backend.facecloud.tevian.ru/api/v1/detect
  face_scan_api_authorization_key: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjUxMjQ0ODMsIm5iZiI6MTcyNTEyNDQ4MywianRpIjoiYTdkMzQwNDUtYzY2MC00NTY3LTkwZTYtYjAyZmFiNjAwZTU2Iiwic3ViIjo0NjIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.juOEpCjilG5Xv4PqomzjTdK3nCsmyO73TdhyKi1RV8U
  face_scan_api_mime_type: image/jpeg